[2025-05-19T13:21:43.080+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-19T13:21:31.706472+00:00/task_id=populate_dimensional_model permission to 509
[2025-05-19T13:21:43.081+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-19T13:21:31.706472+00:00/task_id=populate_dimensional_model permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-19T13:21:31.706472+00:00/task_id=populate_dimensional_model'
[2025-05-19T13:21:43.100+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-19T13:21:31.706472+00:00/task_id=populate_dimensional_model permission to 509
[2025-05-19T13:21:43.100+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-19T13:21:31.706472+00:00/task_id=populate_dimensional_model permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-19T13:21:31.706472+00:00/task_id=populate_dimensional_model'
[2025-05-19T13:21:43.128+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dimensional_model.populate_dimensional_model manual__2025-05-19T13:21:31.706472+00:00 [queued]>
[2025-05-19T13:21:43.134+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dimensional_model.populate_dimensional_model manual__2025-05-19T13:21:31.706472+00:00 [queued]>
[2025-05-19T13:21:43.135+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-05-19T13:21:43.144+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): populate_dimensional_model> on 2025-05-19 13:21:31.706472+00:00
[2025-05-19T13:21:43.149+0000] {standard_task_runner.py:60} INFO - Started process 230 to run task
[2025-05-19T13:21:43.151+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dimensional_model', 'populate_dimensional_model', 'manual__2025-05-19T13:21:31.706472+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/etl_load_postgres_dag.py', '--cfg-path', '/tmp/tmpes59here']
[2025-05-19T13:21:43.152+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask populate_dimensional_model
[2025-05-19T13:21:43.184+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-19T13:21:31.706472+00:00/task_id=populate_dimensional_model permission to 509
[2025-05-19T13:21:43.185+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-19T13:21:31.706472+00:00/task_id=populate_dimensional_model permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-19T13:21:31.706472+00:00/task_id=populate_dimensional_model'
[2025-05-19T13:21:43.186+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_dimensional_model.populate_dimensional_model manual__2025-05-19T13:21:31.706472+00:00 [running]> on host 45d6d00dacb8
[2025-05-19T13:21:43.334+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dimensional_model' AIRFLOW_CTX_TASK_ID='populate_dimensional_model' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T13:21:31.706472+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-19T13:21:31.706472+00:00'
[2025-05-19T13:28:19.797+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-19T13:28:19.806+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_dimensional_model, task_id=populate_dimensional_model, execution_date=20250519T132131, start_date=20250519T132143, end_date=20250519T132819
[2025-05-19T13:28:19.857+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-19T13:28:19.869+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
