[2025-05-18T01:55:03.741+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T01:55:03.008645+00:00/task_id=extract_api permission to 509
[2025-05-18T01:55:03.742+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T01:55:03.008645+00:00/task_id=extract_api permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T01:55:03.008645+00:00/task_id=extract_api'
[2025-05-18T01:55:03.769+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T01:55:03.008645+00:00/task_id=extract_api permission to 509
[2025-05-18T01:55:03.770+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T01:55:03.008645+00:00/task_id=extract_api permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T01:55:03.008645+00:00/task_id=extract_api'
[2025-05-18T01:55:03.802+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dimensional_model.extract_api manual__2025-05-18T01:55:03.008645+00:00 [queued]>
[2025-05-18T01:55:03.809+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dimensional_model.extract_api manual__2025-05-18T01:55:03.008645+00:00 [queued]>
[2025-05-18T01:55:03.809+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-05-18T01:55:03.820+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): extract_api> on 2025-05-18 01:55:03.008645+00:00
[2025-05-18T01:55:03.826+0000] {standard_task_runner.py:60} INFO - Started process 211 to run task
[2025-05-18T01:55:03.828+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dimensional_model', 'extract_api', 'manual__2025-05-18T01:55:03.008645+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/etl_load_postgres_dag.py', '--cfg-path', '/tmp/tmpk3pqevgp']
[2025-05-18T01:55:03.830+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask extract_api
[2025-05-18T01:55:03.874+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T01:55:03.008645+00:00/task_id=extract_api permission to 509
[2025-05-18T01:55:03.875+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T01:55:03.008645+00:00/task_id=extract_api permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T01:55:03.008645+00:00/task_id=extract_api'
[2025-05-18T01:55:03.876+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_dimensional_model.extract_api manual__2025-05-18T01:55:03.008645+00:00 [running]> on host 960d1c61c7d0
[2025-05-18T01:55:04.092+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dimensional_model' AIRFLOW_CTX_TASK_ID='extract_api' AIRFLOW_CTX_EXECUTION_DATE='2025-05-18T01:55:03.008645+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-18T01:55:03.008645+00:00'
[2025-05-18T01:55:05.189+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-18T01:55:05.199+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_dimensional_model, task_id=extract_api, execution_date=20250518T015503, start_date=20250518T015503, end_date=20250518T015505
[2025-05-18T01:55:05.253+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-18T01:55:05.280+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
