[2025-05-21T22:28:37.421+0000] {logging_mixin.py:154} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T22:28:25.988971+00:00/task_id=populate_dimensional_model permission to 509
[2025-05-21T22:28:37.421+0000] {logging_mixin.py:154} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T22:28:25.988971+00:00/task_id=populate_dimensional_model permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T22:28:25.988971+00:00/task_id=populate_dimensional_model'
[2025-05-21T22:28:37.440+0000] {logging_mixin.py:154} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T22:28:25.988971+00:00/task_id=populate_dimensional_model permission to 509
[2025-05-21T22:28:37.441+0000] {logging_mixin.py:154} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T22:28:25.988971+00:00/task_id=populate_dimensional_model permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T22:28:25.988971+00:00/task_id=populate_dimensional_model'
[2025-05-21T22:28:37.468+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dimensional_model.populate_dimensional_model manual__2025-05-21T22:28:25.988971+00:00 [queued]>
[2025-05-21T22:28:37.474+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dimensional_model.populate_dimensional_model manual__2025-05-21T22:28:25.988971+00:00 [queued]>
[2025-05-21T22:28:37.474+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-05-21T22:28:37.483+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): populate_dimensional_model> on 2025-05-21 22:28:25.988971+00:00
[2025-05-21T22:28:37.488+0000] {standard_task_runner.py:57} INFO - Started process 213 to run task
[2025-05-21T22:28:37.490+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dimensional_model', 'populate_dimensional_model', 'manual__2025-05-21T22:28:25.988971+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/etl_load_postgres_dag.py', '--cfg-path', '/tmp/tmpssxci6ny']
[2025-05-21T22:28:37.491+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask populate_dimensional_model
[2025-05-21T22:28:37.525+0000] {logging_mixin.py:154} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T22:28:25.988971+00:00/task_id=populate_dimensional_model permission to 509
[2025-05-21T22:28:37.526+0000] {logging_mixin.py:154} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T22:28:25.988971+00:00/task_id=populate_dimensional_model permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T22:28:25.988971+00:00/task_id=populate_dimensional_model'
[2025-05-21T22:28:37.527+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_dimensional_model.populate_dimensional_model manual__2025-05-21T22:28:25.988971+00:00 [running]> on host 2c8cd8e4a45f
[2025-05-21T22:28:37.587+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dimensional_model' AIRFLOW_CTX_TASK_ID='populate_dimensional_model' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T22:28:25.988971+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T22:28:25.988971+00:00'
[2025-05-21T22:34:57.901+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-21T22:34:57.915+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_dimensional_model, task_id=populate_dimensional_model, execution_date=20250521T222825, start_date=20250521T222837, end_date=20250521T223457
[2025-05-21T22:34:57.940+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-21T22:34:57.954+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
