[2025-05-18T12:35:59.831+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T12:35:52.490194+00:00/task_id=transform_api permission to 509
[2025-05-18T12:35:59.832+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T12:35:52.490194+00:00/task_id=transform_api permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T12:35:52.490194+00:00/task_id=transform_api'
[2025-05-18T12:35:59.857+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T12:35:52.490194+00:00/task_id=transform_api permission to 509
[2025-05-18T12:35:59.858+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T12:35:52.490194+00:00/task_id=transform_api permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T12:35:52.490194+00:00/task_id=transform_api'
[2025-05-18T12:35:59.893+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dimensional_model.transform_api manual__2025-05-18T12:35:52.490194+00:00 [queued]>
[2025-05-18T12:35:59.900+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dimensional_model.transform_api manual__2025-05-18T12:35:52.490194+00:00 [queued]>
[2025-05-18T12:35:59.900+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-05-18T12:35:59.912+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): transform_api> on 2025-05-18 12:35:52.490194+00:00
[2025-05-18T12:35:59.917+0000] {standard_task_runner.py:60} INFO - Started process 224 to run task
[2025-05-18T12:35:59.919+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dimensional_model', 'transform_api', 'manual__2025-05-18T12:35:52.490194+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl_load_postgres_dag.py', '--cfg-path', '/tmp/tmpi1ianmj2']
[2025-05-18T12:35:59.921+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask transform_api
[2025-05-18T12:35:59.963+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T12:35:52.490194+00:00/task_id=transform_api permission to 509
[2025-05-18T12:35:59.964+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T12:35:52.490194+00:00/task_id=transform_api permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T12:35:52.490194+00:00/task_id=transform_api'
[2025-05-18T12:35:59.965+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_dimensional_model.transform_api manual__2025-05-18T12:35:52.490194+00:00 [running]> on host 12957649f5de
[2025-05-18T12:36:00.166+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dimensional_model' AIRFLOW_CTX_TASK_ID='transform_api' AIRFLOW_CTX_EXECUTION_DATE='2025-05-18T12:35:52.490194+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-18T12:35:52.490194+00:00'
[2025-05-18T12:36:00.189+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-18T12:36:00.199+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_dimensional_model, task_id=transform_api, execution_date=20250518T123552, start_date=20250518T123559, end_date=20250518T123600
[2025-05-18T12:36:00.255+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-18T12:36:00.281+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
