[2025-05-18T13:17:15.720+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T13:17:06.790888+00:00/task_id=populate_dimensional_model permission to 509
[2025-05-18T13:17:15.721+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T13:17:06.790888+00:00/task_id=populate_dimensional_model permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T13:17:06.790888+00:00/task_id=populate_dimensional_model'
[2025-05-18T13:17:15.741+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T13:17:06.790888+00:00/task_id=populate_dimensional_model permission to 509
[2025-05-18T13:17:15.741+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T13:17:06.790888+00:00/task_id=populate_dimensional_model permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T13:17:06.790888+00:00/task_id=populate_dimensional_model'
[2025-05-18T13:17:15.770+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dimensional_model.populate_dimensional_model manual__2025-05-18T13:17:06.790888+00:00 [queued]>
[2025-05-18T13:17:15.776+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dimensional_model.populate_dimensional_model manual__2025-05-18T13:17:06.790888+00:00 [queued]>
[2025-05-18T13:17:15.776+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-05-18T13:17:15.786+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): populate_dimensional_model> on 2025-05-18 13:17:06.790888+00:00
[2025-05-18T13:17:15.791+0000] {standard_task_runner.py:60} INFO - Started process 224 to run task
[2025-05-18T13:17:15.793+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dimensional_model', 'populate_dimensional_model', 'manual__2025-05-18T13:17:06.790888+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/etl_load_postgres_dag.py', '--cfg-path', '/tmp/tmpt2dw1zr4']
[2025-05-18T13:17:15.794+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask populate_dimensional_model
[2025-05-18T13:17:15.829+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T13:17:06.790888+00:00/task_id=populate_dimensional_model permission to 509
[2025-05-18T13:17:15.829+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T13:17:06.790888+00:00/task_id=populate_dimensional_model permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T13:17:06.790888+00:00/task_id=populate_dimensional_model'
[2025-05-18T13:17:15.830+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_dimensional_model.populate_dimensional_model manual__2025-05-18T13:17:06.790888+00:00 [running]> on host a5d19bf4c604
[2025-05-18T13:17:15.986+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dimensional_model' AIRFLOW_CTX_TASK_ID='populate_dimensional_model' AIRFLOW_CTX_EXECUTION_DATE='2025-05-18T13:17:06.790888+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-18T13:17:06.790888+00:00'
[2025-05-18T13:23:29.022+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-18T13:23:29.031+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_dimensional_model, task_id=populate_dimensional_model, execution_date=20250518T131706, start_date=20250518T131715, end_date=20250518T132329
[2025-05-18T13:23:29.071+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-18T13:23:29.084+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
